export const en = {
  // Common
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    done: "Done",
    ok: "OK",
    yes: "Yes",
    no: "No",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    search: "Search",
    filter: "Filter",
    refresh: "Refresh",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    close: "Close",
    update: "Update",
    view: "View",
    details: "Details",
    required: "Required",
    optional: "Optional",
    amount: "Amount",
    date: "Date",
    time: "Time",
    note: "Note",
    description: "Description",
    total: "Total",
    status: "Status",
  },

  // Auth
  auth: {
    username: "Username",
    password: "Password",
    loginButton: "Login",
    error: "Error",
    validationError: "Please enter both username and password",
    loginFailed: "Login Failed",
    generalError: "An error occurred during login",
  },

  // Navigation
  nav: {
    home: "Home",
    loans: "Loans",
    customers: "Customers",
    payments: "Payments",
    expenses: "Expenses",
    settings: "Settings",
    businessOverview: "Business Overview",
    funds: "Funds",
    bankAccounts: "Bank Accounts",
    bankDeposits: "Bank Deposits",
    paymentPrediction: "Payment Prediction",
    menu: "Menu",
    welcome: "Welcome",
  },

  // Home Screen
  home: {
    addPayment: "Add Payment",
    duePayments: "Due Payments",
    bankDeposit: "Bank Deposit",
    newLoan: "New Loan",
    systemSummary: "System Summary",
    dueLoansCount: "Due Loans Count",
    todayInstallments: "Today Installments",
    activeLoanCount: "Active Loan Count",
    toBeBanked: "To Be Banked (Rs.)",
  },

  // Customers
  customers: {
    title: "Customers",
    addCustomer: "Add Customer",
    editCustomer: "Edit Customer",
    customerDetails: "Customer Details",
    searchPlaceholder: "Search by name, phone, or NIC...",
    activeCustomers: "Active Customers",
    inactiveCustomers: "Inactive Customers",
    fullName: "Full Name",
    otherNames: "Other Names",
    mobilePhone: "Mobile Phone",
    homePhone: "Home Phone",
    nationalIdNo: "National ID No",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    maritalStatus: "Marital Status",
    ethnicity: "Ethnicity",
    religion: "Religion",
    occupation: "Occupation",
    permanentAddress: "Permanent Address",
    secondaryMobile: "Secondary Mobile",
    whatsappNumber: "WhatsApp Number",
    noCustomers: "No Customers",
    noCustomersMessage:
      "No customers found. Add your first customer to get started.",
    male: "Male",
    female: "Female",
    active: "Active",
    inactive: "Inactive",
    customerHidden: "Customer Hidden",
    customerHiddenMessage:
      "Customer has loans and has been hidden from view but kept in database for accounting purposes.",
    unableToCall: "Unable to make call",
    noSearchResults: "No customers match your search",
    notFound: "Customer not found",
    viewLoans: "View Loans",
    personalInfo: "Personal Information",
    contactInfo: "Contact Information",
    accountInfo: "Account Information",
    createdDate: "Created Date",
    lastUpdated: "Last Updated",
    loadingCustomer: "Loading customer...",
    customerPhoto: "Customer Photo",
    changePhoto: "Change Photo",
    addPhoto: "Add Photo",
    enterFullName: "Enter full name",
    otherNamesLabel: "Other Names",
    enterOtherNames: "Enter other names (optional)",
    permanentAddressLabel: "Permanent Address",
    enterPermanentAddress: "Enter permanent address",
    dateOfBirthLabel: "Date of Birth",
    dateFormat: "YYYY-MM-DD",
    enterNationalId: "Enter national ID number",
    genderLabel: "Gender",
    selectGender: "Select Gender",
    maritalStatusLabel: "Marital Status",
    selectMaritalStatus: "Select Marital Status",
    ethnicityLabel: "Ethnicity",
    selectEthnicity: "Select Ethnicity",
    religionLabel: "Religion",
    selectReligion: "Select Religion",
    occupationLabel: "Occupation",
    enterOccupation: "Enter occupation",
    homePhoneLabel: "Home Phone",
    enterHomePhone: "Enter home phone (optional)",
    mobilePhoneLabel: "Mobile Phone",
    enterMobilePhone: "Enter mobile phone",
    secondaryMobileLabel: "Secondary Mobile",
    enterSecondaryMobile: "Enter secondary mobile (optional)",
    whatsappNumberLabel: "WhatsApp Number",
    enterWhatsappNumber: "Enter WhatsApp number (optional)",
    updating: "Updating...",
    adding: "Adding...",
    updateCustomer: "Update Customer",
    addCustomerButton: "Add Customer",
    takePhoto: "Take Photo",
    chooseFromLibrary: "Choose from Library",
    removePhoto: "Remove Photo",
    permissionRequired: "Permission Required",
    cameraRollPermission: "Permission to access camera roll is required!",
    cameraPermission: "Permission to access camera is required!",
    fillRequiredFields: "Please fill in all required fields",
    customerUpdated: "Customer updated successfully",
    customerAdded: "Customer added successfully",
    failedToUpdate: "Failed to update customer",
    failedToAdd: "Failed to add customer",
    // Gender Options
    genderMale: "Male",
    genderFemale: "Female",
    // Marital Status Options
    maritalSingle: "Single",
    maritalMarried: "Married",
    maritalWidowed: "Widowed",
    maritalDivorced: "Divorced",
    maritalSeparated: "Separated",
    maritalOther: "Other",
    // Ethnicity Options
    ethnicitySinhala: "Sinhala",
    ethnicitySriLankanTamil: "Sri Lankan Tamil",
    ethnicityIndianTamil: "Indian Tamil",
    ethnicitySriLankanMoor: "Sri Lankan Moor",
    ethnicityBurgher: "Burgher",
    ethnicityMalay: "Malay",
    ethnicityMuslim: "Muslim",
    ethnicityOther: "Other",
    // Religion Options
    religionBuddhism: "Buddhism",
    religionHinduism: "Hinduism",
    religionIslam: "Islam",
    religionChristianity: "Christianity",
    religionRomanCatholic: "Roman Catholic",
    religionOther: "Other",
  },

  // Loans
  loans: {
    title: "Loans",
    addLoan: "Create New Loan",
    loanDetails: "Loan Details",
    allLoans: "All Loans",
    activeLoans: "Active",
    completedLoans: "Completed",
    settledLoans: "Settled",
    renewedLoans: "Renewed",
    loanAmount: "Loan Amount",
    interest: "Interest",
    duration: "Duration",
    frequency: "Frequency",
    startDate: "Start Date",
    principal: "Principal",
    totalWithInterest: "Total with Interest",
    totalPaid: "Total Paid",
    outstanding: "Outstanding",
    guarantors: "Guarantors",
    settleLoan: "Settle Loan",
    renewLoan: "Renew Loan",
    paymentPlan: "Payment Plan",
    paymentHistory: "Payment History",
    history: "History",
    noLoans: "No Loans",
    noLoansMessage: "No loans found.",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    months: "months",
    days: "days",
    active: "Active",
    completed: "Completed",
    settled: "Settled",
    renewed: "Renewed",
    defaulted: "Defaulted",
    searchPlaceholder: "Search by customer, amount, phone...",
    amount: "Amount",
    interestRate: "Interest",
    loansFor: "Loans for",
    loan: "loan",
    loansPlural: "loans",
    filtered: "(filtered)",
    new: "New",
    noLoansMatch: "No loans match your search",
    noLoansForCustomer: "No loans found for this customer",
    noLoansFound: "No loans found",
    openEnded: "Open-ended",
    month: "month",
    monthPlural: "months",
    day: "day",
    dayPlural: "days",
    // Loan Details Screen
    loadingLoanDetails: "Loading loan details...",
    loanNotFound: "Loan not found",
    id: "ID",
    actions: "Actions",
    viewDetails: "View Details",
    name: "Name",
    mobile: "Mobile",
    timeline: "Timeline",
    created: "Created",
    updated: "Updated",
    settleConfirmTitle: "Settle Loan",
    settleConfirmMessage:
      "This will create a payment of Rs. {amount} to settle the entire outstanding balance and mark the loan as SETTLED.\n\nDo you want to proceed?",
    settleButton: "Settle Loan",
    settleSuccess: "Loan has been settled successfully!",
    settleError: "Failed to settle loan. Please try again.",
    renewLoanTitle: "Renew Loan - {loanId}",
    outstandingBalanceLabel: "Outstanding Balance",
    enterNewCapitalLabel: "Enter new capital amount to add:",
    enterAmountPlaceholder: "Enter amount",
    renewConfirmMessage: "Are you sure you want to renew this loan?",
    yesRenew: "Yes, Renew",
    invalidAmountTitle: "Invalid Amount",
    invalidAmountMessage: "Please enter a valid amount for new capital.",
    settlePayAmount: "Settle Loan (Pay Rs. {amount})",
    // Add Loan Screen
    createNewLoan: "Create New Loan",
    loadingCustomers: "Loading customers...",
    renewingLoan: "🔄 Renewing Loan {loanNumber}",
    previousOutstanding: "Previous Outstanding",
    newCapitalAdded: "New Capital Added",
    newLoanTotal: "New Loan Total",
    loanApplicationForm: "Loan Application Form",
    customer: "Customer",
    selectCustomer: "Select Customer",
    enterLoanAmount: "Enter loan amount",
    interestPer30Days: "Interest (per 30 days) %",
    enterInterestRate: "Enter interest rate",
    selectFrequency: "Select Frequency",
    enterStartDate: "Enter start date",
    durationInMonths: "Duration in Months",
    enterDurationMonths: "Enter duration in months (optional)",
    durationInDays: "Duration in Days",
    enterDurationDays: "Enter duration in days (optional)",
    guarantorsOptional: "Guarantors (Optional)",
    selectGuarantor: "Select Guarantor",
    addGuarantor: "Add Guarantor",
    noGuarantorsAdded: "No guarantors added yet",
    remove: "Remove",
    createLoan: "Create Loan",
    creating: "Creating...",
    // Validation Messages
    errorSelectGuarantor: "Please select a guarantor",
    errorGuarantorSameAsApplicant: "Guarantor cannot be the same as applicant",
    errorGuarantorAlreadyAdded: "This guarantor is already added",
    errorSelectCustomer: "Please select a customer",
    errorValidLoanAmount: "Please enter a valid loan amount",
    errorValidInterestRate: "Please enter a valid interest rate",
    errorSelectFrequency: "Please select a payment frequency",
    errorEnterStartDate: "Please enter a start date",
    errorEnterDuration: "Please enter either duration in months or days",
    errorFailedToLoadCustomers: "Failed to load customers",
    errorFailedToCreateLoan: "Failed to create loan application",
    // Success Messages
    loanRenewedSuccess: "Loan Renewed Successfully",
    loanRenewedMessage:
      "Previous loan {oldLoanNumber} has been marked as RENEWED.\n\nNew loan has been created and is now ACTIVE.",
    viewLoans: "View Loans",
    loanCreatedSuccess: "Loan application created successfully",
    // Active Loan Warning
    activeLoanExists: "Active Loan Exists",
    activeLoanExistsMessage:
      "{customerName} already has an active loan. Please complete all existing loans before creating a new one.",
  },

  // Payments
  payments: {
    title: "Payments",
    paymentHistory: "Payment History",
    paymentPlan: "Payment Plan",
    banked: "Banked",
    unbanked: "Unbanked",
    // Due Payments Screen
    duePaymentsTitle: "Due Payments",
    loadingDuePayments: "Loading due payments...",
    totalLoans: "Total Loans",
    overdue: "Overdue",
    dueToday: "Due Today",
    allCaughtUp: "All Caught Up!",
    noPendingPayments: "No pending payments at the moment",
    loan: "Loan",
    overdueLabel: "Overdue",
    dueTodayLabel: "Due Today",
    installmentAmount: "Installment Amount",
    totalOutstanding: "Total Outstanding",
    remainingInstallments: "Remaining Installments",
    collectPayment: "Collect Payment",
    // Payment Plan Screen
    loadingPaymentPlan: "Loading payment plan...",
    paymentPlanNotAvailable: "Payment plan not available",
    paymentSummary: "Payment Summary",
    principalAmount: "Principal Amount",
    totalAmount: "Total Amount",
    perInstallment: "Per Installment",
    numberOfPayments: "Number of Payments",
    frequency: "Frequency",
    paymentSchedule: "Payment Schedule",
    no: "No.",
    dueDate: "Due Date",
    payment: "Payment",
    balance: "Balance",
    print: "⎙ Print",
    sharePDF: "⤴ Share PDF",
    failedToLoadPaymentPlan: "Failed to load payment plan",
    failedToPrint: "Failed to print payment plan",
    sharingNotAvailable: "Sharing is not available on this device",
    failedToShare: "Failed to share payment plan",
    // PDF Content
    companyName: "Sinha Investment",
    loanPaymentPlan: "Loan Payment Plan",
    customerName: "Customer Name",
    mobileNumber: "Mobile Number",
    loanDate: "Loan Date",
    loanStatus: "Loan Status",
    interestRate: "Interest Rate",
    perThirtyDays: "per 30 days",
    duration: "Duration",
    months: "months",
    paymentFrequency: "Payment Frequency",
    totalAmountWithInterest: "Total Amount (with Interest)",
    installmentAmount: "Installment Amount",
    numberOfInstallments: "Number of Installments",
    generatedOn: "Generated on",
    computerGenerated:
      "This is a computer-generated document. No signature is required.",
    // Payment History Screen
    loadingPaymentHistory: "Loading payment history...",
    noPaymentHistoryFound: "No payment history found",
    paymentHistoryTitle: "Payment History",
    totalLoanAmount: "Total Loan Amount",
    outstandingBalance: "Outstanding Balance",
    paymentDate: "Payment Date",
    paymentAmount: "Payment Amount",
    date: "Date",
    failedToLoadPaymentHistory: "Failed to load payment history",
    failedToPrintPaymentHistory: "Failed to print payment history",
    failedToSharePaymentHistory: "Failed to share payment history",
    loanId: "Loan ID",
    // Payments List Screen
    loadingPayments: "Loading payments...",
    activeLoans: "Active Loans",
    today: "Today",
    paymentsCount: "payment",
    paymentsCountPlural: "payments",
    loan: "Loan",
    time: "Time",
    noPaymentsFound: "No payments found",
    noUnbankedPaymentsToday: "No unbanked payments received today",
    noPaymentsToday: "No payments received today",
    allPaymentsBanked: "All payments have been banked",
    noPaymentsAvailable: "No payments available",
    // Add Payment Screen
    paymentDetails: "Payment Details",
    customer: "Customer",
    selectCustomer: "Select Customer",
    selectLoan: "Select Loan",
    paymentAmount: "Payment Amount",
    enterPaymentAmount: "Enter payment amount",
    paymentNote: "Payment Note",
    enterPaymentNote: "Enter payment note (optional)",
    recordPayment: "Record Payment",
    recording: "Recording...",
    loanInformation: "Loan Information",
    loanAmount: "Loan Amount",
    outstandingBalance: "Outstanding Balance",
    pleaseSelectCustomer: "Please select a customer",
    pleaseSelectLoan: "Please select a loan",
    pleaseEnterValidAmount: "Please enter a valid payment amount",
    paymentExceedsBalance:
      "Payment amount (Rs. {amount}) exceeds outstanding balance (Rs. {outstanding}). Do you want to continue?",
    continue: "Continue",
    paymentRecordedSuccess: "Payment recorded successfully",
    viewPaymentHistory: "View Payment History",
    failedToRecordPayment: "Failed to record payment",
    failedToLoadCustomersLoans: "Failed to load customers and loans",
    // Payment Prediction Screen
    paymentPrediction: "Payment Prediction",
    selectDateRange: "Select Date Range",
    fromDate: "From Date",
    toDate: "To Date",
    predictPayments: "Predict Payments",
    predictionSummary: "Prediction Summary",
    totalExpectedPayments: "Total Expected Payments",
    totalExpectedAmount: "Total Amount",
    expectedPayments: "Expected Payments",
    predictionInfo:
      "This amount represents expected payments from active loans within the selected period. This can help determine available funds for new loans.",
    noPredictedPayments: "No expected payments in this date range",
    predictionError: "Failed to predict payments",
    invalidDateRange: "Start date must be before or equal to end date",
    showExpectedPayments: "Show Expected Payments",
    hideExpectedPayments: "Hide Expected Payments",
  },

  // Expenses
  expenses: {
    title: "Expenses",
    addExpense: "Add Expense",
    editExpense: "Edit Expense",
    totalExpenses: "Total Expenses",
    claimed: "Claimed",
    unclaimed: "Unclaimed",
    enterAmount: "Enter amount",
    enterDescription: "Enter description",
    noExpenses: "No Expenses",
    noExpensesMessage: "Tap the + button to add your first expense.",
    cannotEdit: "Cannot Edit",
    cannotEditMessage: "This expense has been claimed and cannot be edited.",
    cannotDelete: "Cannot Delete",
    cannotDeleteMessage: "This expense has been claimed and cannot be deleted.",
    deleteExpense: "Delete Expense",
    deleteConfirmMessage:
      "Are you sure you want to delete this expense?\n\nAmount: Rs. {amount}\nDescription: {description}",
    expenseLabel: "EXPENSE",
    claimedBadge: "CLAIMED",
    invalidAmount: "Invalid Amount",
    invalidAmountMessage: "Please enter a valid amount",
    invalidDescription: "Invalid Description",
    invalidDescriptionMessage: "Please enter a description",
    invalidDate: "Invalid Date",
    invalidDateMessage: "Please select a date",
    expenseAddedSuccess: "Expense added successfully",
    expenseUpdatedSuccess: "Expense updated successfully",
    expenseDeletedSuccess: "Expense deleted successfully",
    failedToSave: "Failed to save expense. Please try again.",
    failedToDelete: "Failed to delete expense. Please try again.",
  },

  // Bank Deposits
  bankDeposits: {
    title: "Bank Deposits",
    selectBankAccount: "Select Bank Account",
    depositToBank: "Deposit to Bank Account",
    noSelection: "No Selection",
    noSelectionMessage:
      "Please select at least one payment or expense to deposit.",
    noPayments: "No Payments",
    noPaymentsMessage:
      "You must select at least one payment to make a deposit.",
    noBankAccounts: "No Bank Accounts",
    noBankAccountsMessage:
      "Please add a bank account first in Settings > Bank Accounts.",
    confirmDeposit: "Confirm Deposit",
    depositSuccess: "Success",
    depositError: "Error",
    unbankedPayments: "Unbanked Payments",
    noUnbankedPayments: "No Unbanked Payments",
    noUnbankedPaymentsMessage:
      "All payments have been deposited and expenses have been claimed.",
    totalAmount: "Total Amount",
    netDeposit: "Net Deposit",
    selected: "selected",
    // Loading & Empty States
    loadingPayments: "Loading payments...",
    noItemsToDeposit: "No Items to Deposit",
    allDeposited:
      "All payments have been deposited and expenses have been claimed.",
    // Controls
    selectAll: "Select All",
    deselectAll: "Deselect All",
    // Summary
    payments: "Payments",
    expenses: "Expenses",
    totalDeposit: "Total Deposit",
    // Payment Card
    loan: "Loan",
    date: "Date",
    time: "Time",
    note: "Note",
    // Expense Card
    expense: "EXPENSE",
    // Section Headers
    paymentsCount: "Payments ({count})",
    // Deposit Confirmation
    paymentsLabel: "Payments: {count} (Rs. {amount})",
    expensesLabel: "Expenses: {count} (Rs. {amount})",
    netDepositLabel: "Net Deposit: Rs. {amount}",
    totalDepositLabel: "Total Deposit: Rs. {amount}",
    toLabel: "To: {nickname}",
    bankLabel: "{bank}",
    accountLabel: "Account: {accountNumber}",
    // Success Messages
    depositedSuccess: "Successfully deposited {count} payment{s}",
    depositedSuccessWithExpenses:
      "Successfully deposited {paymentCount} payment{paymentS} and claimed {expenseCount} expense{expenseS} to the bank account.",
    and: " and ",
    claimedExpenses: "claimed {count} expense{s}",
    toBankAccount: " to the bank account.",
    // Errors
    failedToLoad: "Failed to load data. Please try again.",
    failedToDeposit: "Failed to deposit. Please try again.",
  },

  // Bank Accounts
  bankAccounts: {
    title: "Bank Accounts",
    addBankAccount: "Add Bank Account",
    editBankAccount: "Edit Bank Account",
    nickname: "Nickname",
    accountName: "Account Name",
    accountNumber: "Account Number",
    bank: "Bank",
    branch: "Branch",
    noBankAccounts: "No Bank Accounts",
    noBankAccountsMessage: "No bank accounts found. Add your first account.",
    // Button Text
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    update: "Update",
    // Empty State
    noAccountsTitle: "No Bank Accounts",
    noAccountsSubtitle: "Add a bank account to start managing deposits",
    // Form Labels
    nicknameLabel: "Nickname *",
    nicknameHint: "Short name to identify this account",
    nicknamePlaceholder: "e.g., Main Account, Savings",
    accountNameLabel: "Account Name *",
    accountNameHint: "Official account holder name",
    accountNamePlaceholder: "Enter account name",
    accountNumberLabel: "Account Number *",
    accountNumberPlaceholder: "Enter account number",
    bankLabel: "Bank *",
    bankPlaceholder: "Enter bank name",
    branchLabel: "Branch *",
    branchPlaceholder: "Enter branch name",
    // Card Labels
    accountNameCard: "Account Name",
    accountNumberCard: "Account Number",
    branchCard: "Branch",
    // Alerts
    deleteTitle: "Delete Bank Account",
    deleteMessage: "Are you sure you want to delete {accountName}?",
    deleteSuccess: "Bank account deleted successfully",
    deleteError: "Failed to delete bank account",
    saveSuccess: "Bank account added successfully",
    updateSuccess: "Bank account updated successfully",
    saveError: "Failed to save bank account",
    validationError: "Please fill in all fields",
    loadError: "Failed to load bank accounts",
  },

  // Funds
  funds: {
    title: "Funds",
    addFund: "Add Fund",
    editFund: "Edit Fund",
    selectBankAccount: "Select Bank Account",
    fundAmount: "Fund Amount",
    fundNote: "Fund Note",
    fundDate: "Fund Date",
    totalFunds: "Total Funds",
    noFunds: "No Funds",
    noFundsMessage: "No funds recorded yet.",
    // Loading
    loadingFunds: "Loading funds...",
    loadingBankAccounts: "Loading bank accounts...",
    // Summary
    totalFundsInvested: "Total Funds Invested",
    fundEntries: "fund entries",
    fundEntry: "fund entry",
    // Empty State
    noFundsFound: "No funds found",
    tapToAddFunds: "Tap the + button to add funds",
    // Delete
    deleteFund: "Delete Fund",
    deleteFundMessage: "Are you sure you want to delete this fund entry?",
    fundDeletedSuccess: "Fund deleted successfully",
    fundDeleteError: "Failed to delete fund",
    // Form
    infoMessage:
      "Add funds that were credited to your bank account for loan releases",
    amountLabel: "Amount (Rs)",
    amountPlaceholder: "Enter amount",
    bankAccountLabel: "Bank Account",
    selectBankAccountPlaceholder: "Select Bank Account",
    dateLabel: "Date",
    datePlaceholder: "YYYY-MM-DD",
    dateHint: "Format: YYYY-MM-DD (e.g., 2025-11-07)",
    noteLabel: "Note",
    notePlaceholder: "Optional note",
    required: "*",
    // Buttons
    updateFund: "Update Fund",
    cancel: "Cancel",
    // Validation
    validationError: "Validation Error",
    invalidAmount: "Please enter a valid amount greater than 0",
    selectBankAccountError: "Please select a bank account",
    enterDateError: "Please enter a date",
    noBankAccountsTitle: "No Bank Accounts",
    noBankAccountsMessage:
      "Please add a bank account first before creating funds.",
    // Success/Error
    fundUpdatedSuccess: "Fund updated successfully",
    fundAddedSuccess: "Fund added successfully",
    saveError: "Failed to save fund entry",
    loadBankAccountsError: "Failed to load bank accounts",
  },

  // Business Overview
  businessOverview: {
    title: "Business Overview",
    subtitle: "Real-time insights of your lending business",
    financialSummary: "Financial Summary",
    outstandingBalance: "Outstanding Balance",
    fromAllActiveLoans: "From all active loans",
    totalFundInvested: "Total Fund Invested",
    capitalDeployed: "Capital deployed",
    currentProfit: "Current Profit",
    profitFormula: "Outstanding - Fund Invested - Expenses",
    totalExpenses: "Total Expenses",
    operationalExpenses: "Operational expenses (claimed)",
    businessMetrics: "Business Metrics",
    activeLoans: "Active Loans",
    completed: "Completed",
    customers: "Customers",
    overdue: "Overdue",
    operations: "Operations",
    pendingDeposits: "Pending Deposits",
    pendingDepositsHint: "Unbanked payments awaiting deposit",
    lastUpdated: "Last updated",
    pullToRefresh: "Pull down to refresh",
    loadingOverview: "Loading overview...",
    failedToLoad: "Failed to load data",
  },

  // Settings
  settings: {
    title: "Settings",
    bankAccounts: "Bank Accounts",
    bankAccountsDesc: "Manage your bank accounts",
    funds: "Funds",
    fundsDesc: "Track your fund investments",
    businessOverview: "Business Overview",
    businessOverviewDesc: "View business insights and analytics",
    language: "Language",
    languageDesc: "Change application language",
    smsNotification: "SMS Notification",
    smsNotificationDesc: "Configure SMS notification number",
    logout: "Logout",
    logoutConfirm: "Are you sure you want to logout?",
    selectLanguage: "Select Language",
    english: "English",
    sinhala: "සිංහල (Sinhala)",
    languageChanged: "Language Changed",
    languageChangedMessage: "The application language has been updated.",
    account: "Account",
    username: "Username",
    userType: "User Type",
    appInfo: "App Information",
    version: "Version",
    build: "Build",
    notifications: "Notifications",
    bankDepositSMS: "Bank Deposit SMS Number",
    notConfigured: "Not configured",
    smsHint: "💡 Receive SMS notifications when bank deposits are made",
    editSMSTitle: "Edit SMS Notification Number",
    smsPlaceholder: "Enter phone number (e.g., +94771234567)",
  },

  // Messages
  messages: {
    saveSuccess: "Saved successfully",
    saveError: "Failed to save. Please try again.",
    deleteSuccess: "Deleted successfully",
    deleteError: "Failed to delete. Please try again.",
    updateSuccess: "Updated successfully",
    updateError: "Failed to update. Please try again.",
    loadError: "Failed to load data. Please try again.",
    networkError: "Network error. Please check your connection.",
    invalidInput: "Invalid input. Please check your data.",
    confirmDelete: "Are you sure you want to delete this item?",
  },
};
